---
spring:    
  resources:
    add-mappings: true
  security:
    user:
      name: user
      password: user

application:
  users:
    - name: user@think.com
      password: '{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG'
      roles:
        - USER
    - name: admin@think.com
      password: '{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG'
      roles:
        - USER
        - ADMIN