---
spring:
  resources:
    add-mappings: true

application:
  users:
    - name: user@localhost.local
      password: '{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG'
      roles:
        - USER
    - name: admin@localhost.local
      password: '{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG'
      roles:
        - USER
        - ADMIN